In [67]:
import cv2
import numpy as np
import os

In [41]:
img = cv2.imread('test_photo_verticaly.jpg')

In [43]:
print(len(img), len(img[0]))

In [30]:
cropped_img = img[60:860, 60:1259]

In [34]:
directory = '/home/damian/Pictures/slub/JPG_wybrane_DO_PUBLIKACJI'

In [1]:
for i, file in enumerate(os.listdir(directory)):
    
    filename = os.fsdecode(file)
    img = cv2.imread(os.path.join(directory, filename))
    if len(img) < 1000:
        cropped_img = img[60:860, 60:1259] # photo horizontaly
    else:
        cropped_img = img[64:1263, 64:864] # photo verticaly
        
    j = str(i + 1)
    
    # Saving a file with file name like "photo###"
    newfilename = f"cropped_photos/photo{str(j).zfill(3)}.jpg"

    cv2.imwrite(newfilename, cropped_img)

NameError: name 'os' is not defined

In [46]:
for i, j in enumerate(img):
    print(i, j[64])

0 [255 255 255]
1 [255 255 255]
2 [255 255 255]
3 [255 255 255]
4 [255 255 255]
5 [255 255 255]
6 [255 255 255]
7 [255 255 255]
8 [255 255 255]
9 [255 255 255]
10 [255 255 255]
11 [255 255 255]
12 [255 255 255]
13 [255 255 255]
14 [255 255 255]
15 [255 255 255]
16 [255 255 255]
17 [255 255 255]
18 [255 255 255]
19 [255 255 255]
20 [255 255 255]
21 [255 255 255]
22 [255 255 255]
23 [255 255 255]
24 [255 255 255]
25 [255 255 255]
26 [255 255 255]
27 [255 255 255]
28 [255 255 255]
29 [255 255 255]
30 [255 255 255]
31 [255 255 255]
32 [255 255 255]
33 [255 255 255]
34 [255 255 255]
35 [255 255 255]
36 [255 255 255]
37 [255 255 255]
38 [255 255 255]
39 [255 255 255]
40 [255 255 255]
41 [255 255 255]
42 [255 255 255]
43 [255 255 255]
44 [255 255 255]
45 [255 255 255]
46 [255 255 255]
47 [255 255 255]
48 [255 255 255]
49 [255 255 255]
50 [255 255 255]
51 [255 255 255]
52 [255 255 255]
53 [255 255 255]
54 [255 255 255]
55 [255 255 255]
56 [255 255 255]
57 [255 255 255]
58 [255 255 255]
59 [255

In [45]:
for i in range(50):
    print(img[425 + i][864], img[425 + i][865])

[ 8 23 55] [255 255 255]
[11 26 59] [255 255 255]
[10 28 59] [255 255 254]
[10 29 64] [255 255 255]
[14 31 70] [255 255 255]
[16 34 75] [255 255 255]
[19 37 78] [255 255 255]
[20 39 82] [255 255 255]
[23 42 85] [255 255 255]
[25 44 87] [255 255 255]
[29 48 91] [255 255 255]
[32 53 98] [254 254 254]
[ 39  62 108] [255 255 255]
[ 51  74 124] [255 255 255]
[ 66  90 142] [255 255 255]
[ 79 106 156] [255 255 255]
[ 96 121 165] [255 255 255]
[113 134 172] [255 255 255]
[126 145 178] [255 255 255]
[132 149 182] [255 255 255]
[134 151 184] [255 255 255]
[134 151 184] [255 255 255]
[130 147 180] [255 255 255]
[123 143 174] [255 255 255]
[123 138 164] [255 255 255]
[125 139 157] [253 255 255]
[158 167 170] [255 255 254]
[178 182 183] [255 255 255]
[184 186 187] [255 255 255]
[192 191 195] [255 255 255]
[194 195 199] [255 255 255]
[195 194 198] [255 255 255]
[196 195 197] [255 255 255]
[192 191 193] [255 255 255]
[178 181 185] [255 255 255]
[166 170 181] [255 255 255]
[143 155 167] [255 255 255]


In [44]:
for i, j in enumerate(img[450]):
    print(i, j)

0 [255 255 255]
1 [255 255 255]
2 [255 255 255]
3 [255 255 255]
4 [255 255 255]
5 [255 255 255]
6 [255 255 255]
7 [255 255 255]
8 [255 255 255]
9 [255 255 255]
10 [255 255 255]
11 [255 255 255]
12 [255 255 255]
13 [255 255 255]
14 [255 255 255]
15 [255 255 255]
16 [255 255 255]
17 [255 255 255]
18 [255 255 255]
19 [255 255 255]
20 [255 255 255]
21 [255 255 255]
22 [255 255 255]
23 [255 255 255]
24 [255 255 255]
25 [255 255 255]
26 [255 255 255]
27 [255 255 255]
28 [255 255 255]
29 [255 255 255]
30 [255 255 255]
31 [255 255 255]
32 [255 255 255]
33 [255 255 255]
34 [255 255 255]
35 [255 255 255]
36 [255 255 255]
37 [255 255 255]
38 [255 255 255]
39 [255 255 255]
40 [255 255 255]
41 [255 255 255]
42 [255 255 255]
43 [255 255 255]
44 [255 255 255]
45 [255 255 255]
46 [255 255 255]
47 [255 255 255]
48 [255 255 255]
49 [255 255 255]
50 [255 255 255]
51 [255 255 255]
52 [255 255 255]
53 [255 255 255]
54 [255 255 255]
55 [255 255 255]
56 [255 255 255]
57 [255 255 255]
58 [255 255 255]
59 [255